<?php declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StoreInfoExtra\ViewModel\StoreInfoExtra;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var StoreInfoExtra $storeInfoExtra */

$storeInfoExtra = $block->getData('viewModelStoreInfo');
?>

<?php if ($coc = $storeInfoExtra->getCoCNumber()): ?>
    <div><?= $escaper->escapeHtml(__('CoC number %1', $coc)); ?></div>
<?php endif; ?>
